// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzpbsridzmqrcztafzip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cGJzcmlkem1xcmN6dGFmemlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDcxMjAsImV4cCI6MjA1NTk4MzEyMH0.Oxzh-NId5MAypfN8UUFPE5yhecT1HlXhan4iIU7jmpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);